version: '2'
services:
    common-app:
        image: snv-development/service-common
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - 'SPRING_PROFILES_ACTIVE=prod,swagger'
            - 'EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka'
            - 'SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config'
            - 'SPRING_DATASOURCE_URL=jdbc:mysql://mysql5.7:3306/snv_common?useUnicode=true&characterEncoding=utf8&useSSL=false'
            - 'SPRING_DATASOURCE_USERNAME=hvm'
            - 'SPRING_DATASOURCE_PASSWORD=hvm!@#456'
            #- JHIPSTER_SLEEP=30
            - JHIPSTER_REGISTRY_PASSWORD=admin
        networks:
          - snv-devnet
              
networks:
  snv-devnet:
    external:
      name: network-snv-dev
